### ISSUE TITLE
Things model visualization

### ISSUE THREAD

**Issue by mhtb32** [Bambil/bamboolia#1]
- [ ] I think we can add a picture, in addition to the already-have table, to visualize a thing model and its parameters in a beautiful way. We can add a graphical example for each parameter to make it more understandable.
- [ ] What suggestions you have for the user to consider when he/she is defining his/her things model? I think it's good to list them too in this readme.
- [x] I suggest having a third column in the table expressing examples.

**Comment by 1995parham** [comment]
@mhtb32 what do you think about our new README? Is it enough to express our awesome language? 😂

**Comment by mhtb32** [comment]
It's fairly better now, Though you can complete the model with other properties considering Uncle Sepehr has invented a lamp with all those features(like state feedback and so on)
